version: '3'

services:

  # Databases
  game_server_db:
    image: mariadb:10.3
    env_file: game_server/environment/server_env

  redis:
    image: redis:alpine
    container_name: redis

  # Service
  game_server:
    build: .    
    image: game_server:devel
    restart: on-failure
    container_name: game_server_container
    command: >
      sh -c "make migrate &&
             gunicorn -w 3 game_server.wsgi:application -b :11000"
    env_file: game_server/environment/server_env
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "11000"
    depends_on:
      - game_server_db
      - redis

  # nginx
  nginx:
    build: ./nginx/
    container_name: game_server_nginx
    ports:
      - "11000:11000"
      - "443:443"
    restart: on-failure
    volumes:
      - static_data:/app/static
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - game_server


volumes:
  static_data:
