# Generated by Django 2.1.4 on 2021-09-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0003_entity_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logged',
            field=models.BooleanField(null=True),
        ),
    ]
