# Generated by Django 2.1.4 on 2022-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0005_entity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_hp', models.IntegerField(default=200)),
                ('current_mp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=200)),
                ('max_mp', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=10)),
                ('magic', models.IntegerField(default=10)),
                ('spirit', models.IntegerField(default=10)),
                ('experience', models.IntegerField(default=0)),
                ('next_lv', models.IntegerField(default=1)),
                ('lv', models.IntegerField(default=1)),
                ('max_range', models.IntegerField(default=1)),
                ('movement', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('additional_range', models.IntegerField(default=0)),
                ('area_of_effect', models.IntegerField(default=1)),
                ('effect_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
