# Generated by Django 2.1.4 on 2022-01-24 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goblins', '0006_character_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='goblins.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
