# Generated by Django 2.1.4 on 2022-01-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0007_auto_20220124_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='goblin_class',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
