# Generated by Django 2.1.7 on 2022-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0009_auto_20220201_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.BinaryField(default=b'{"x":0, "y":0}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='logged',
            field=models.BooleanField(null=True),
        ),
    ]
