# Generated by Django 2.1.7 on 2022-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0010_auto_20220201_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
