# Generated by Django 2.1.7 on 2022-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0011_auto_20220201_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='map_area',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
