# Generated by Django 2.1.7 on 2022-02-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0012_character_map_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='server_instance',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
