# Generated by Django 2.1.7 on 2022-02-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0013_auto_20220201_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='maparea',
            name='server_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goblins.ServerInstance'),
            preserve_default=False,
        ),
    ]
