# Generated by Django 2.1.7 on 2022-02-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goblins', '0014_maparea_server_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinstance',
            name='reference',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
    ]
